### ISSUE TITLE
Rename the repo ephs.club?

### ISSUE THREAD

**Issue by andrewgazelka** [ephs/ephs.club#8]
Since we have moved off of [ephs.github.io](ephs.github.io), I think it makes sense to rename the repo [ephs.club](ephs.club). Opinions?

**Comment by AlecDusheck** [comment]
+1

**Comment by andrewgazelka** [comment]
Done

**Comment by ritikmishra** [comment]
+1

On Sep 22, 2018 7:45 PM, "Andrew Gazelka" <notifications@github.com> wrote:

Closed #8 <https://github.com/ephs/ephs.club/issues/8>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ephs/ephs.club/issues/8#event-1861806624>, or mute the
thread
